### ISSUE TITLE
Error while installing in macOS Sierra with brew

### ISSUE THREAD

**Issue by rpussente** [dflemstr/rq#142]
```sh
➜  ~ brew install --HEAD rq
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
dub                      libical                  libical-glib             links

==> Installing rq from dflemstr/tools
==> Installing dependencies for dflemstr/tools/rq: dflemstr/tools/v8
==> Installing dflemstr/tools/rq dependency: dflemstr/tools/v8
==> Downloading https://github.com/v8/v8/archive/5.6.222.tar.gz
Already downloaded: /Users/rpussente/Library/Caches/Homebrew/v8-5.6.222.tar.gz
mv /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/AUTHORS /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/benchmarks /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/BUILD.gn /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/build_overrides /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/ChangeLog /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/CODE_OF_CONDUCT.md /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/codereview.settings /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/DEPS /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/docs /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/gni /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/gypfiles /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/include /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/infra /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/LICENSE /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/LICENSE.fdlibm /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/LICENSE.strongtalk /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/LICENSE.v8 /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/LICENSE.valgrind /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/Makefile /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/Makefile.android /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/OWNERS /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/PRESUBMIT.py /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/README.md /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/samples /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/snapshot_toolchain.gni /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/src /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/test /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/testing /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/third_party /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/tools /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/WATCHLISTS /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/.brew_home /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/.clang-format /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/.gitignore /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/.gn /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/.ycm_extra_conf.py /private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/v8
==> Cloning https://chromium.googlesource.com/chromium/tools/depot_tools.git
Updating /Users/rpussente/Library/Caches/Homebrew/v8--depot_tools--git
==> Checking out revision 850ce84cb68f6b428fa3a490f7b08481285fffb9
==> gclient config https://github.com/v8/v8.git
==> gclient sync -v --no-history -r 5.6.222
Last 15 lines from /Users/rpussente/Library/Logs/Homebrew/v8/02.gclient:
[0:00:24] Receiving objects:  10% (773/7725), 2.67 MiB | 1.31 MiB/s
[0:00:25] Receiving objects:  18% (1391/7725), 5.05 MiB | 1.65 MiB/s
[0:00:27] Receiving objects:  23% (1802/7725), 14.10 MiB | 2.97 MiB/s
[0:00:28] Receiving objects:  90% (6953/7725), 21.64 MiB | 4.33 MiB/s
[0:00:28] remote: Total 7725 (delta 2984), reused 3069 (delta 1468), pack-reused 0
[0:00:28] Receiving objects: 100% (7725/7725), 21.64 MiB | 4.33 MiB/s
[0:00:28] Resolving deltas:   0% (0/2984)
[0:00:28] Resolving deltas:  10% (300/2984)
[0:00:28] Resolving deltas: 100% (2984/2984)
[0:00:28] Checking connectivity... done.

________ running 'git -c core.deltaBaseCacheLimit=2g fetch origin --verbose' in '/private/tmp/v8-20161202-71810-1610pgl/v8-5.6.222/v8'
[0:00:31] From https://github.com/v8/v8
[0:00:31]  = [up to date]      master     -> origin/master
----------------------------------------
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `dump': can't dump IO (TypeError)
	from /usr/local/Homebrew/Library/Homebrew/build.rb:191:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:180:in `<main>'
Error: marshal data too short
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:373:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:609:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:266:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:478:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:441:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:441:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:441:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:203:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:268:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:161:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by dflemstr** [comment]
I think I've fixed the compilation issue but the build will still be really slow because there's no pre-compiled Sierra build.

I'm not a Mac user and the Travis build times out (takes too long) if I try to build it there so I'm not sure how I can provide a nice homebrew package for this use-case.
